### ISSUE TITLE
add backspace button 

### ISSUE THREAD

**Issue by Sar-taj107** [Sar-taj107/Basic-Calculator#1]
add backspace button to the existing application if you want to do please let me know i will assign.
or if you want add more operators.

**Comment by AayushPaigwar** [comment]
Hello @Sar-taj107  
I am interested in adding a backspace button please assign it to me.

**Comment by Sar-taj107** [comment]
Sure @AayushPaigwar 
Thanks for showing interest please go ahead!

**Comment by Kedarnath-Rothe** [comment]
please assign this issue to me

**Comment by Sar-taj107** [comment]
sure @Kedarnath-Rothe 
if you can do this please just start contributing, 
send pull request and give a star to this repo to show your support!  i will accept you PR.
